max_lr: 0.01
weight_decay: 0.0001
momentum: 0.9
max_epochs: 50
batch_size: 128

in_channels: 3
num_classes: 100
use_pretrained_weights: true

test_model: False
checkpoint_path: #checkpoints/*****.ckpt used for testing / fine-tuning
early_stopping_patience: 10
num_workers: 16
check_val_every_n_epoch: 3

wandb_project: CIFAR100
wandb_experiment_name: resnet_50

train_split_ratio: 0.8
data_root: ./data
checkpoint_folder: ./checkpoints/


