name: pl_env
dependencies:
  - pip
  - python=3.10
  - pip:
      - numpy==1.26.3
      - scikit-learn==1.4.0
      - torch==2.1.2
      - torchvision==0.16.2
      - tqdm==4.66.1
      - matplotlib==3.8.2
      - notebook
      - lightning
      - wandb
      - munch
      - ipykernel
      - ipywidgets
      

